### ISSUE TITLE
Квазицитаты

### ISSUE THREAD

**Issue by dpwiz** [neclitoris/safeboard#1]
Сплайсы конечно работают, но окавычивать большие многострочные куски baseXX довольно неудобно.
У квазицитат поприятнее использование.

**Comment by neclitoris** [comment]
Как ни искал, не смог найти способ дать квазицитате узнать, а какой тип вообще ожидается от выражения, чтобы понять, является ли вообще строчка baseXX-закодированным вектором (укладывается ли там ровно n элементов). Хочется ловить побольше ошибок при компиляции, поэтому и выбрал типизированный сплайс.
Строчку при желании можно сделать с помощью `Text.RawString.QQ.r` внутри сплайса. Не очень удобно, к сожалению, но Template Haskell навешивает такие ограничения.

**Comment by dpwiz** [comment]
Интересный поинт 🤔

А если разделить на два прохода? В одном байты достаются из цитаты, а в другом конверсия с проверками?

**Comment by neclitoris** [comment]
Можно так сделать, но тогда конверсия уйдёт в рантайм, и ошибка будет уже в рантайме.

**Comment by dpwiz** [comment]
Цитата внутри сплайса не прокатит? :sweat_smile:

**Comment by neclitoris** [comment]
Собственно, что и предлагается использовать, если не хочется использовать строковые литералы:
```haskell
import Text.RawString.QQ

example :: Vector Word8
example = $$(base64 [r|
    ZXhhbX
    BsZQ==
|])
```

Можно, наверное, подкрутить, чтобы получилось что-то вроде
```haskell
example = $$([base64|
    ZXhhbX
    BsZQ==
|])
```
, но не знаю, станет ли от такого изменения сильно удобнее)

**Comment by dpwiz** [comment]
Да, makes sense.
